# Generated by Django 5.1.7 on 2025-03-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_us_text', models.TextField(blank=True, null=True, verbose_name='متن درباره ما')),
                ('contact_us_text', models.TextField(blank=True, null=True, verbose_name='متن تماس با ما')),
                ('address', models.CharField(blank=True, max_length=250, null=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=250, null=True, verbose_name='شماره تلفن')),
                ('email', models.CharField(blank=True, max_length=250, null=True, verbose_name='ایمیل')),
                ('copy_right', models.CharField(max_length=255, verbose_name='متن کپی رایت')),
                ('instagram_link', models.CharField(blank=True, default='https://instagram.com/username', max_length=250, null=True, verbose_name='لینک اینستاگرام')),
                ('telegram_link', models.CharField(blank=True, default='https://t.me/username', max_length=250, null=True, verbose_name='لینک تلگرام')),
            ],
        ),
    ]
