# Generated by Django 5.1.7 on 2025-03-15 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sitesettings_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='شماره تلفن'),
        ),
    ]
