# Generated by Django 5.1.7 on 2025-03-19 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_article_status_alter_article_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='similar_articles',
            field=models.ManyToManyField(blank=True, null=True, related_name='similar', to='blog.article', verbose_name='مقالات مشابه'),
        ),
    ]
