# Generated by Django 5.1.7 on 2025-03-15 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='اسم بازیگر')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('description', models.TextField(verbose_name='درباره بازیگر')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='actor_thumbnails/', verbose_name='تصویر بازیگر')),
                ('gender', models.CharField(choices=[('man', 'مرد'), ('woman', 'زن')], default='man', max_length=10, verbose_name='جنسیت')),
                ('date_birth', models.DateField(verbose_name='تاریخ تولد')),
                ('place_birth', models.CharField(max_length=300, verbose_name='محل تولد')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس شود'), ('published', 'منتشر شود')], default='published', max_length=10, verbose_name='وضعیت')),
            ],
            options={
                'verbose_name': 'بازیگر',
                'verbose_name_plural': 'بازیگران',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True, verbose_name='عنوان ژانر')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='نامک')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='genre_thumbnails/', verbose_name='تصویر ژانر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
            ],
            options={
                'verbose_name': 'ژانر',
                'verbose_name_plural': 'ژانر ها',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='زبان')),
            ],
            options={
                'verbose_name': 'زبان',
                'verbose_name_plural': 'زبان ها',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='شناسه محتوا')),
                ('body', models.TextField(verbose_name='نظر')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس شود'), ('published', 'منتشر شود')], default='published', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='نوع محتوا')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نظر',
                'verbose_name_plural': 'نظرات',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان فیلم')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('description', models.TextField(verbose_name='خلاصه داستان')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='movie_thumbnails/', verbose_name='تصویر فیلم')),
                ('country', models.CharField(max_length=30, verbose_name='کشور سازنده')),
                ('director', models.CharField(max_length=200, verbose_name='اسم کارگردان')),
                ('duration', models.CharField(max_length=5, verbose_name='مدت زمان فیلم (لطفاً مدت زمان را به دقیقه وارد کنید)')),
                ('release_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('score', models.CharField(default='0.0/10', max_length=10, verbose_name='امتیاز')),
                ('age_range', models.CharField(default='بالای 14 سال', max_length=20, verbose_name='رنج سنی')),
                ('views', models.IntegerField(default=0, verbose_name='بازدید ها')),
                ('trailer', models.URLField(max_length=500, verbose_name='لینک تریلر فیلم')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس شود'), ('published', 'منتشر شود')], default='published', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('actors', models.ManyToManyField(related_name='movies', to='movie.actor', verbose_name='بازیگران')),
                ('movie_genre', models.ManyToManyField(related_name='movies_genre', to='movie.genre', verbose_name='ژانر')),
                ('movie_language', models.ManyToManyField(related_name='movies_language', to='movie.language', verbose_name='زبان فیلم')),
                ('similar_movies', models.ManyToManyField(blank=True, null=True, related_name='similar', to='movie.movie', verbose_name='فیلم های مشابه')),
            ],
            options={
                'verbose_name': 'فیلم',
                'verbose_name_plural': 'فیلم ها',
            },
        ),
        migrations.CreateModel(
            name='MovieImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='movie_images/', verbose_name='تصاویر فیلم')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_images', to='movie.movie', verbose_name='فیلم مربوطه')),
            ],
            options={
                'verbose_name': 'تصویر فیلم',
                'verbose_name_plural': 'تصاویر فیلم ها',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True, verbose_name='عنوان سریال')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='نامک')),
                ('description', models.TextField(verbose_name='خلاصه داستان')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='series_thumbnails/', verbose_name='تصویر سریال')),
                ('country', models.CharField(max_length=30, verbose_name='کشور سازنده')),
                ('director', models.CharField(max_length=200, verbose_name='اسم کارگردان')),
                ('duration', models.CharField(max_length=5, verbose_name='مدت زمان سریال (لطفاً مدت زمان را به دقیقه وارد کنید)')),
                ('chapter_count', models.PositiveIntegerField(verbose_name='تعداد فصل ها')),
                ('release_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('score', models.CharField(max_length=10, verbose_name='امتیاز')),
                ('age_range', models.CharField(default='بالای 14 سال', max_length=20, verbose_name='رنج سنی')),
                ('views', models.IntegerField(default=0, verbose_name='بازدید ها')),
                ('trailer', models.URLField(max_length=500, verbose_name='لینک تریلر سریال')),
                ('status', models.CharField(choices=[('draft', 'پیش نویس شود'), ('published', 'منتشر شود')], default='published', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('actors', models.ManyToManyField(related_name='series', to='movie.actor', verbose_name='بازیگران')),
                ('series_genre', models.ManyToManyField(related_name='series_genre', to='movie.genre', verbose_name='ژانر')),
                ('series_language', models.ManyToManyField(related_name='series_language', to='movie.language', verbose_name='زبان سریال')),
                ('similar_series', models.ManyToManyField(blank=True, null=True, related_name='similar', to='movie.series', verbose_name='سریال های مشابه')),
            ],
            options={
                'verbose_name': 'سریال',
                'verbose_name_plural': 'سریال ها',
            },
        ),
        migrations.CreateModel(
            name='ChapterSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name='عنوان فصل')),
                ('order', models.PositiveIntegerField(verbose_name='ترتیب فصل')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ به\u200cروزرسانی')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.series', verbose_name='سریال مربوطه')),
            ],
            options={
                'verbose_name': 'فصل سریال',
                'verbose_name_plural': 'فصل های سریال',
            },
        ),
        migrations.CreateModel(
            name='SeriesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, null=True, upload_to='series_images/', verbose_name='تصاویر سریال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='series_images', to='movie.series', verbose_name='سریال مربوطه')),
            ],
            options={
                'verbose_name': 'تصویر سریال',
                'verbose_name_plural': 'تصاویر سریال ها',
            },
        ),
        migrations.CreateModel(
            name='VideoMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_480p', models.URLField(blank=True, null=True, verbose_name='لینک کیفیت 480p')),
                ('subtitle_480p', models.CharField(blank=True, max_length=255, null=True, verbose_name='زیرنویس کیفیت 480p')),
                ('quality_720p', models.URLField(blank=True, null=True, verbose_name='لینک کیفیت 720p')),
                ('subtitle_720p', models.CharField(blank=True, max_length=255, null=True, verbose_name='زیرنویس کیفیت 720p')),
                ('quality_1080p', models.URLField(blank=True, null=True, verbose_name='لینک کیفیت 1080p')),
                ('subtitle_1080p', models.CharField(blank=True, max_length=255, null=True, verbose_name='زیرنویس کیفیت 1080p')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.movie', verbose_name='فیلم مربوطه')),
            ],
            options={
                'verbose_name': 'ویدیو های فیلم',
                'verbose_name_plural': 'ویدیو های فیلم',
            },
        ),
        migrations.CreateModel(
            name='VideoSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_480p', models.URLField(blank=True, null=True, verbose_name='لینک کیفیت 480p')),
                ('subtitle_480p', models.CharField(blank=True, max_length=255, null=True, verbose_name='زیرنویس کیفیت 480p')),
                ('quality_720p', models.URLField(blank=True, null=True, verbose_name='لینک کیفیت 720p')),
                ('subtitle_720p', models.CharField(blank=True, max_length=255, null=True, verbose_name='زیرنویس کیفیت 720p')),
                ('quality_1080p', models.URLField(blank=True, null=True, verbose_name='لینک کیفیت 1080p')),
                ('subtitle_1080p', models.CharField(blank=True, max_length=255, null=True, verbose_name='زیرنویس کیفیت 1080p')),
                ('order', models.PositiveIntegerField(unique=True, verbose_name='ترتیب ویدیو')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.chapterseries', verbose_name='فصل مربوطه')),
            ],
            options={
                'verbose_name': 'ویدیو سریال',
                'verbose_name_plural': 'ویدیو های سریال',
            },
        ),
    ]
