# Generated by Django 5.1.7 on 2025-03-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=300, verbose_name='کشور سازنده'),
        ),
        migrations.AlterField(
            model_name='series',
            name='country',
            field=models.CharField(max_length=300, verbose_name='کشور سازنده'),
        ),
    ]
