# Generated by Django 5.1.7 on 2025-03-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_country_alter_series_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='score',
            field=models.CharField(default='0.0/10', max_length=10, verbose_name='امتیاز'),
        ),
    ]
