# Generated by Django 5.1.7 on 2025-03-15 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_rename_movie_language_movie_language_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_recommended',
            field=models.BooleanField(default=False, verbose_name='آیا فیلم، پیشنهادی است؟'),
        ),
    ]
