# Generated by Django 5.1.7 on 2025-03-15 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_movie_is_recommended'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_genre',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='series',
            old_name='series_genre',
            new_name='genre',
        ),
    ]
