# Generated by Django 5.1.7 on 2025-03-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_moviecomment_seriescomment_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='views',
            field=models.IntegerField(default=0, verbose_name='بازدید ها'),
        ),
    ]
