# Generated by Django 5.1.7 on 2025-03-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_actor_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videomovie',
            name='subtitle_1080p',
        ),
        migrations.RemoveField(
            model_name='videomovie',
            name='subtitle_480p',
        ),
        migrations.RemoveField(
            model_name='videomovie',
            name='subtitle_720p',
        ),
        migrations.AddField(
            model_name='movie',
            name='subtitle_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک زیرنویس فیلم'),
        ),
        migrations.AddField(
            model_name='series',
            name='subtitle_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='لینک زیرنویس سریال'),
        ),
    ]
