# Generated by Django 5.1.7 on 2025-03-17 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0009_remove_videomovie_subtitle_1080p_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videoseries',
            name='subtitle_1080p',
        ),
        migrations.RemoveField(
            model_name='videoseries',
            name='subtitle_480p',
        ),
        migrations.RemoveField(
            model_name='videoseries',
            name='subtitle_720p',
        ),
    ]
