# Generated by Django 5.1.7 on 2025-03-18 00:35

import movie.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0013_remove_series_quality_1080p_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=movie.models.movie_image_upload_to, verbose_name='اسکرین شات فیلم'),
        ),
        migrations.AlterField(
            model_name='seriesimage',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=movie.models.series_image_upload_to, verbose_name='اسکرین شات سریال'),
        ),
    ]
